import type { Metadata } from "next";
import { inter } from "@/components/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cube Solver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
